# This is a basic workflow that is manually triggered
# This is a basic workflow that is manually triggered

name: Dynamic Secrets USER INPUT workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
  workflow_dispatch:
    # inputs:
    #   secrets_list:
    #     description: 'Comma-separated list of secrets to print'
    #     required: true
    #     default: 'AZURE_TOKEN,AZURE_SECRET_TOKEN'
    inputs:
      my_secrets:
        description: "list of secrets to fetch"
        required: true
      my_vars:
        description: "VARIABLES TO RETRIEVE: "  
        required: true
       
   
jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Check
        uses: actions/checkout@v3

      # Install jq if not already installed
      - name: Install jq
        run: |
          if ! command -v jq &> /dev/null; then
            sudo apt-get update
            sudo apt-get install jq -y
          fi
      - name: Print GitHub Environment Variables
        run: |
          env  
          
       # View the secrets context
      - name: View secrets context
        run: echo "${{ toJson(secrets) }}"
        
      - name: Print Secrets
        env:
          SECRETS: '${{ toJson(secrets) }}'
          # INPUT_SECRETS_LIST: '${{ github.event.inputs.secrets_list }}'
         
        run: |
          IFS=',' read -ra string_array <<< ${{ github.event.inputs.my_secrets }}

          for secret in "${string_array[@]}"; do
            value="$(jq -r --arg key "$secret" '.[$key]' <<< "$SECRETS" | sed 's|.|& |g')"
            echo "$secret: $value"
            echo "$secret=$value" >> $GITHUB_ENV
          done

      - name: Print input variables
        run: |
              IFS=',' read -ra vars_array <<< "${{ github.event.inputs.my_vars }}"
              for var in "${vars_array[@]}"; do
                value="${!var}"
                echo "$var: $value"
              done
        env:
            COLOR: ${{ vars.COLOR }}
            COMPANY: ${{ vars.COMPANY }} 
            GREET: ${{ vars.GREET }}
            MEDIUM: ${{ vars.MEDIUM }}      
            
      # - name: 
        # run: |
        #   for secret in A B; do
        #     value="$(jq -r --arg key "$secret" '.[$key]' <<< "$SECRETS" | sed 's|.|& |g')"
        #     echo "$secret: $value"
        #   done
        # run: |
        #   IFS=',' read -ra SECRETS_ARRAY <<< "$INPUT_SECRETS_LIST"
        #   for secret in "${SECRETS_ARRAY[@]}"; do
        #     value="$(jq -r --arg key "$secret" '.[$key]' <<< "$SECRETS" | sed 's|.|& |g')"
        #     echo "$secret: $value"
        #   done
