# This is a basic workflow that is manually triggered

name: Dynamic Secrets workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
  workflow_dispatch:
   
jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Check
        uses: actions/checkout@v3

      # Install jq if not already installed
      - name: Install jq
        run: |
          if ! command -v jq &> /dev/null; then
            sudo apt-get update
            sudo apt-get install jq -y
          fi
      - name: Print GitHub Environment Variables
        run: |
          env  
          
       # View the secrets context
      - name: View secrets context
        run: echo "${{ toJson(secrets) }}"
        
      - name: Print Secrets
        env:
          SECRETS: '${{ toJson(secrets) }}'
          
        # run: |
        #   for secret in A B; do
        #     value="$(jq -r --arg key "$secret" '.[$key]' <<< "$SECRETS" | sed 's|.|& |g')"
        #     echo "$secret: $value"
        #   done
        run: |
          IFS=',' read -ra SECRETS_ARRAY <<< "$INPUT_SECRETS_LIST"
          for secret in "${SECRETS_ARRAY[@]}"; do
            value="$(jq -r --arg key "$secret" '.[$key]' <<< "$SECRETS" | sed 's|.|& |g')"
            echo "$secret: $value"
          done
