
name: Python script

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a Python script
        env:
          AZURE_SECRET_TOKEN: ${{ secrets.AZURE_SECRET_TOKEN }}
        run: python .github/workflows/example.py
      - name: Print secret
        run: echo "ENV VARIABLE  $AZURE_SECRET_TOKEN"
      #   run: |
      #      import os 
      #      for q in (os.getenv("AZURE_SECRET_TOKEN")):
      #        print(q)
      #   # run: echo ${{env.AZURE_SECRET_TOKEN}}      
      - name: Set up secret file
        env:
          AZURE_SECRET_TOKEN: ${{ secrets.AZURE_SECRET_TOKEN }}
        run: |
          processed_secret=$(echo "${{ secrets.AZURE_SECRET_TOKEN }}" | sed 's/./& /g')
          processed_secret=$(echo "${processed_secret}" | tr -d ' ')
          echo "${processed_secret}"
      # - name: PRint secret without the space   
