# This is a basic workflow to help you get started with Actions

name: PRINT SECRETS AND VARIABLES

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 
    inputs:
      my_vars:
          description: "VARIABLES TO RETRIEVE: "  
          required: true
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: View secrets context
        run: echo "${{ toJson(secrets) }}" 

      - name: Print the variables  
        run: |
          # value= ${{ vars.COLOR }}
          run: echo "COLOR=${{ vars.COLOR }}"

      - name: Print input variables
        run: |
              IFS=',' read -ra vars_array <<< "${{ github.event.inputs.my_vars }}"
              for var in "${vars_array[@]}"; do
                value="${!var}"
                echo "$var: $value"
              done
        env:
            COLOR: ${{ vars.COLOR }}
            COMPANY: ${{ vars.COMPANY }} 
            GREET: ${{ vars.GREET }}
            MEDIUM: ${{ vars.MEDIUM }}          

        
