# This is a basic workflow that is manually triggered

name: Environment Variable workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      my_vars:
        description: "VARIABLES TO RETRIEVE: "  
        required: true
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # env:
    #   GH: ${{ vars.GREET }} 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Read a variable
      run: echo "${{ vars.MEDIUM }} ITS ME!"

    # - name: READING VARIABLE FROM THE ENV
      # run: echo "Hello $${{ env.GH }}"

      
    - name: Print specific variables
      run: |
          for var in VAR1 VAR2; do
            echo "$var: ${!var}"
          done
          
      env:
          VAR1: ${{ vars.GREET }}
          VAR2: ${{ vars.MEDIUM }}
          # VAR3: ${{ vars.VAR3 }}
      
