 # This is a basic workflow that is manually triggered

name: Environment Variable workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      my_vars:
        description: "VARIABLES TO RETRIEVE: "  
        required: true
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    # Runs a single command using the runners shell
    - name: Read a variable
      run: echo "${{ vars.MEDIUM }} ITS ME!"
 
    - name: Print given variables
      run: |
          for var in VAR1 VAR2; do
            echo "$var: ${!var}"
          done        
      env:
          VAR1: ${{ vars.GREET }}
          VAR2: ${{ vars.MEDIUM }}
               
    - name: Print input variables
      run: |
          IFS=',' read -ra vars_array <<< "${{ github.event.inputs.my_vars }}"
          for var in "${vars_array[@]}"; do
            value="${!var}"
            echo "$var: ${!var}"
          done  
    
